---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  dbname: wordpress
  password: admin
  dbuser: admin
  dbpass: admin

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
stringData:
  admin_user: admin
  admin_pw: admin1

---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
type: Opaque
stringData:
  INFLUXDB_DATABASE: influxdb
  INFLUXDB_USERNAME: root
  INFLUXDB_PASSWORD: root
  INFLUXDB_HOST: MINIKUBE_IP

---
apiVersion: v1
kind: Secret
metadata:
  name: pma-secret
type: Opaque
stringData:
  dbname: wordpress
  dbuser: admin
  dbpass: admin
  password: admin

---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secret
type: Opaque
stringData:
  INFLUXDB_DB: influxdb
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_USER: root
  INFLUXDB_USER_PASSWORD: root
